/**
 * QuirkyHome Visual Page Builder â€” Section Registry
 * 
 * Maps each SectionType to its metadata, default settings,
 * and the field schema used by the dynamic sidebar editor.
 */

import type { SectionDefinition } from "./types";

export const sectionRegistry: SectionDefinition[] = [
  {
    type: "HeroBanner",
    label: "Hero Banner",
    icon: "Image",
    category: "hero",
    description: "Catchy main banner with headline and CTA",
    fields: [
      { key: "heading", label: "Heading", type: "text", defaultValue: "Buy Home Decor Items Online for Every Indian Home" },
      { key: "subheading", label: "Subheading", type: "textarea", defaultValue: "Shop bedsheets, wall decor, table lamps, kitchen essentials, dining pieces, planters, gifts, and curated home accessories at friendly prices." },
      { key: "badgeText", label: "Badge Text", type: "text", defaultValue: "Festive Home Refresh Sale" },
      { key: "button1Text", label: "Primary Button Text", type: "text", defaultValue: "Shop the Sale" },
      { key: "button1Link", label: "Primary Button Link", type: "text", defaultValue: "/category/wall-decor" },
      { key: "button2Text", label: "Secondary Button Text", type: "text", defaultValue: "Explore Collections" },
      { key: "button2Link", label: "Secondary Button Link", type: "text", defaultValue: "/search" },
      { key: "imageUrl", label: "Background Image URL", type: "image", defaultValue: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=80" },
      { key: "feature1", label: "Feature 1", type: "text", defaultValue: "Fast delivery" },
      { key: "feature2", label: "Feature 2", type: "text", defaultValue: "Secure checkout" },
      { key: "feature3", label: "Feature 3", type: "text", defaultValue: "Curated picks" },
    ],
    defaultSettings: {
      heading: "Buy Home Decor Items Online for Every Indian Home",
      subheading: "Shop bedsheets, wall decor, table lamps, kitchen essentials, dining pieces, planters, gifts, and curated home accessories at friendly prices.",
      badgeText: "Festive Home Refresh Sale",
      button1Text: "Shop the Sale",
      button1Link: "/category/wall-decor",
      button2Text: "Explore Collections",
      button2Link: "/search",
      imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=80",
      feature1: "Fast delivery",
      feature2: "Secure checkout",
      feature3: "Curated picks",
    },
  },
  {
    type: "SearchBand",
    label: "Search Band",
    icon: "Search",
    category: "utility",
    description: "Quick search bar with suggested keywords",
    fields: [
      { key: "label", label: "Label", type: "text", defaultValue: "Search for" },
      { key: "chips", label: "Chips (comma separated)", type: "text", defaultValue: "Bedsheets, Wall Art, Lamps, Planters" },
    ],
    defaultSettings: {
      label: "Search for",
      chips: "Bedsheets, Wall Art, Lamps, Planters",
    },
  },
  {
    type: "CategoryGrid",
    label: "Category Grid",
    icon: "Grid",
    category: "content",
    description: "Grid of product categories with images",
    fields: [
      { key: "eyebrow", label: "Eyebrow Text", type: "text", defaultValue: "Shop by category" },
      { key: "heading", label: "Heading", type: "text", defaultValue: "Home decor, furnishing and essentials" },
      { key: "subheading", label: "Subheading", type: "text", defaultValue: "Find bedding, wall decor, lighting, kitchen, dining, bath, garden, gifts, storage and showpieces in one place." },
      { key: "categoryCount", label: "Number of Categories", type: "number", defaultValue: 5 },
      { key: "cat1Text", label: "Category 1 Text", type: "text", defaultValue: "Bedding" },
      { key: "cat1Image", label: "Category 1 Image", type: "image", defaultValue: "" },
      { key: "cat1Link", label: "Category 1 Link", type: "text", defaultValue: "/bedding" },
      { key: "cat2Text", label: "Category 2 Text", type: "text", defaultValue: "Furnishing" },
      { key: "cat2Image", label: "Category 2 Image", type: "image", defaultValue: "" },
      { key: "cat2Link", label: "Category 2 Link", type: "text", defaultValue: "/furnishing" },
      { key: "cat3Text", label: "Category 3 Text", type: "text", defaultValue: "Organiser" },
      { key: "cat3Image", label: "Category 3 Image", type: "image", defaultValue: "" },
      { key: "cat3Link", label: "Category 3 Link", type: "text", defaultValue: "/organiser" },
      { key: "cat4Text", label: "Category 4 Text", type: "text", defaultValue: "Bath" },
      { key: "cat4Image", label: "Category 4 Image", type: "image", defaultValue: "" },
      { key: "cat4Link", label: "Category 4 Link", type: "text", defaultValue: "/bath" },
      { key: "cat5Text", label: "Category 5 Text", type: "text", defaultValue: "Gifts" },
      { key: "cat5Image", label: "Category 5 Image", type: "image", defaultValue: "" },
      { key: "cat5Link", label: "Category 5 Link", type: "text", defaultValue: "/gifts" },
      { key: "cat6Text", label: "Category 6 Text", type: "text", defaultValue: "New Arrival" },
      { key: "cat6Image", label: "Category 6 Image", type: "image", defaultValue: "" },
      { key: "cat6Link", label: "Category 6 Link", type: "text", defaultValue: "/new-arrival" },
      { key: "cat7Text", label: "Category 7 Text", type: "text", defaultValue: "Comforters" },
      { key: "cat7Image", label: "Category 7 Image", type: "image", defaultValue: "" },
      { key: "cat7Link", label: "Category 7 Link", type: "text", defaultValue: "/comforters" },
      { key: "cat8Text", label: "Category 8 Text", type: "text", defaultValue: "Carpet" },
      { key: "cat8Image", label: "Category 8 Image", type: "image", defaultValue: "" },
      { key: "cat8Link", label: "Category 8 Link", type: "text", defaultValue: "/carpet" },
      { key: "cat9Text", label: "Category 9 Text", type: "text", defaultValue: "Return and Exchange" },
      { key: "cat9Image", label: "Category 9 Image", type: "image", defaultValue: "" },
      { key: "cat9Link", label: "Category 9 Link", type: "text", defaultValue: "/return-and-exchange" },
      { key: "cat10Text", label: "Category 10 Text", type: "text", defaultValue: "Category 10" },
      { key: "cat10Image", label: "Category 10 Image", type: "image", defaultValue: "" },
      { key: "cat10Link", label: "Category 10 Link", type: "text", defaultValue: "/category-10" },
      { key: "cat11Text", label: "Category 11 Text", type: "text", defaultValue: "Category 11" },
      { key: "cat11Image", label: "Category 11 Image", type: "image", defaultValue: "" },
      { key: "cat11Link", label: "Category 11 Link", type: "text", defaultValue: "/category-11" },
      { key: "cat12Text", label: "Category 12 Text", type: "text", defaultValue: "Category 12" },
      { key: "cat12Image", label: "Category 12 Image", type: "image", defaultValue: "" },
      { key: "cat12Link", label: "Category 12 Link", type: "text", defaultValue: "/category-12" },
    ],
    defaultSettings: {
      eyebrow: "Shop by category",
      heading: "Home decor, furnishing and essentials",
      subheading: "Find bedding, wall decor, lighting, kitchen, dining, bath, garden, gifts, storage and showpieces in one place.",
      categoryCount: 5,
      cat1Text: "Bedding",
      cat1Image: "",
      cat1Link: "/bedding",
      cat2Text: "Furnishing",
      cat2Image: "",
      cat2Link: "/furnishing",
      cat3Text: "Organiser",
      cat3Image: "",
      cat3Link: "/organiser",
      cat4Text: "Bath",
      cat4Image: "",
      cat4Link: "/bath",
      cat5Text: "Gifts",
      cat5Image: "",
      cat5Link: "/gifts",
      cat6Text: "New Arrival",
      cat6Image: "",
      cat6Link: "/new-arrival",
      cat7Text: "Comforters",
      cat7Image: "",
      cat7Link: "/comforters",
      cat8Text: "Carpet",
      cat8Image: "",
      cat8Link: "/carpet",
      cat9Text: "Return and Exchange",
      cat9Image: "",
      cat9Link: "/return-and-exchange",
      cat10Text: "Category 10",
      cat10Image: "",
      cat10Link: "/category-10",
      cat11Text: "Category 11",
      cat11Image: "",
      cat11Link: "/category-11",
      cat12Text: "Category 12",
      cat12Image: "",
      cat12Link: "/category-12",
    },
  },
  {
    type: "CollectionsSection",
    label: "Collections Section",
    icon: "FolderOpen",
    category: "content",
    description: "Showcase of curated collections",
    fields: [
      { key: "eyebrow", label: "Eyebrow Text", type: "text", defaultValue: "Collections" },
      { key: "heading", label: "Heading", type: "text", defaultValue: "Shop by collection" },
      { key: "subheading", label: "Subheading", type: "text", defaultValue: "Curated product sets to help you discover your style." },
    ],
    defaultSettings: {
      eyebrow: "Collections",
      heading: "Shop by collection",
      subheading: "Curated product sets to help you discover your style.",
    },
  },
  {
    type: "ProductGrid",
    label: "Product Grid",
    icon: "Grid3x3",
    category: "product",
    description: "Dynamic list of products from catalog",
    fields: [
      { key: "eyebrow", label: "Eyebrow Text", type: "text", defaultValue: "Sale picks" },
      { key: "heading", label: "Heading", type: "text", defaultValue: "Premium finds, friendly prices" },
      { key: "subheading", label: "Subheading", type: "text", defaultValue: "Shop bestselling home decor products with clear pricing, ratings, wishlist and add-to-cart actions." },
    ],
    defaultSettings: {
      eyebrow: "Sale picks",
      heading: "Premium finds, friendly prices",
      subheading: "Shop bestselling home decor products with clear pricing, ratings, wishlist and add-to-cart actions.",
    },
  },
  {
    type: "PromisesSection",
    label: "Promises Section",
    icon: "ShieldCheck",
    category: "trust",
    description: "Trust badges and brand promises",
    fields: [
      { key: "eyebrow", label: "Eyebrow Text", type: "text", defaultValue: "Why choose us" },
      { key: "heading", label: "Heading", type: "text", defaultValue: "A calmer, warmer way to shop for home" },
    ],
    defaultSettings: {
      eyebrow: "Why choose us",
      heading: "A calmer, warmer way to shop for home",
    },
  },
  {
    type: "Newsletter",
    label: "Newsletter Signup",
    icon: "Mail",
    category: "form",
    description: "Email signup form for updates",
    fields: [
      { key: "eyebrow", label: "Eyebrow Text", type: "text", defaultValue: "Decor notes" },
      { key: "heading", label: "Heading", type: "text", defaultValue: "Ideas, offers and new drops" },
      { key: "subheading", label: "Subheading", type: "text", defaultValue: "Get room styling inspiration, festive sale alerts and new home essentials in your inbox." },
      { key: "buttonText", label: "Button Text", type: "text", defaultValue: "Join Newsletter" },
    ],
    defaultSettings: {
      eyebrow: "Decor notes",
      heading: "Ideas, offers and new drops",
      subheading: "Get room styling inspiration, festive sale alerts and new home essentials in your inbox.",
      buttonText: "Join Newsletter",
    },
  },
  {
    type: "SeoArticle",
    label: "SEO Article",
    icon: "FileText",
    category: "content",
    description: "SEO-friendly content with heading and paragraph fields",
    fields: [
      {
        key: "headingTag",
        label: "Heading Level",
        type: "select",
        defaultValue: "h2",
        options: [
          { label: "H1", value: "h1" },
          { label: "H2", value: "h2" },
          { label: "H3", value: "h3" },
          { label: "H4", value: "h4" },
          { label: "H5", value: "h5" },
          { label: "H6", value: "h6" },
        ],
      },
      { key: "headingText", label: "Main Heading", type: "text", defaultValue: "QuirkyHome - Buy Home Decor Items Online in India" },
      { key: "content", label: "Content Paragraph 1", type: "textarea", defaultValue: "QuirkyHome is built for people who want beautiful home decor without making shopping feel complicated. Explore bedding, home furnishing, wall decor, table lamps, dining essentials, kitchen products, bath accessories, planters, storage baskets, showpieces and thoughtful gifts for Indian homes." },
      {
        key: "subheadingTag",
        label: "Second Heading Level",
        type: "select",
        defaultValue: "h2",
        options: [
          { label: "H1", value: "h1" },
          { label: "H2", value: "h2" },
          { label: "H3", value: "h3" },
          { label: "H4", value: "h4" },
          { label: "H5", value: "h5" },
          { label: "H6", value: "h6" },
        ],
      },
      { key: "subheadingText", label: "Second Heading", type: "text", defaultValue: "Shop Home Decor by Category" },
      { key: "content2", label: "Content Paragraph 2", type: "textarea", defaultValue: "Whether you are refreshing a bedroom, setting up a living room, styling a dining table or choosing a housewarming gift, our category-led shopping experience helps you find the right product quickly. Every product card keeps price, discount, rating, wishlist and add-to-cart actions easy to scan on mobile and desktop." },
    ],
    defaultSettings: {
      headingTag: "h2",
      headingText: "QuirkyHome - Buy Home Decor Items Online in India",
      content: "QuirkyHome is built for people who want beautiful home decor without making shopping feel complicated. Explore bedding, home furnishing, wall decor, table lamps, dining essentials, kitchen products, bath accessories, planters, storage baskets, showpieces and thoughtful gifts for Indian homes.",
      subheadingTag: "h2",
      subheadingText: "Shop Home Decor by Category",
      content2: "Whether you are refreshing a bedroom, setting up a living room, styling a dining table or choosing a housewarming gift, our category-led shopping experience helps you find the right product quickly. Every product card keeps price, discount, rating, wishlist and add-to-cart actions easy to scan on mobile and desktop.",
    },
  },

  {
    type: "BannerStrip",
    label: "Announcement Bar",
    icon: "Megaphone",
    category: "hero",
    description: "Announcement strip for the top of the page",
    fields: [
      { key: "text", label: "Announcement Text", type: "text", defaultValue: "Free shipping on orders above â‚¹999!" },
      { key: "bgColor", label: "Background Color", type: "color", defaultValue: "#008060" },
      { key: "textColor", label: "Text Color", type: "color", defaultValue: "#ffffff" },
      { key: "link", label: "Link (optional)", type: "text", defaultValue: "" },
    ],
    defaultSettings: {
      text: "Free shipping on orders above â‚¹999!",
      bgColor: "#008060",
      textColor: "#ffffff",
      link: "",
    },
  },

  /* â”€â”€â”€ Image Grid (3 images with links â€” Flipkart/Amazon style) â”€â”€ */
  {
    type: "ImageGrid",
    label: "Image Grid",
    icon: "LayoutGrid",
    category: "media",
    description: "3-image promotional grid with clickable links (1 large + 2 small)",
    fields: [
      { key: "image1Url", label: "Image 1 URL (Large â€” Left)", type: "image", defaultValue: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80" },
      { key: "image1Link", label: "Image 1 Link", type: "text", defaultValue: "/", placeholder: "/collections/lamps" },
      { key: "image1Alt", label: "Image 1 Alt Text", type: "text", defaultValue: "Lamps & Lighting" },
      { key: "image2Url", label: "Image 2 URL (Top Right)", type: "image", defaultValue: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=800&q=80" },
      { key: "image2Link", label: "Image 2 Link", type: "text", defaultValue: "/", placeholder: "/collections/showpieces" },
      { key: "image2Alt", label: "Image 2 Alt Text", type: "text", defaultValue: "Showpieces & Vases" },
      { key: "image3Url", label: "Image 3 URL (Bottom Right)", type: "image", defaultValue: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80" },
      { key: "image3Link", label: "Image 3 Link", type: "text", defaultValue: "/", placeholder: "/collections/furniture" },
      { key: "image3Alt", label: "Image 3 Alt Text", type: "text", defaultValue: "Accent Furniture" },
      { key: "gap", label: "Gap Between Images (px)", type: "number", defaultValue: 12, min: 0, max: 32 },
      { key: "borderRadius", label: "Border Radius (px)", type: "number", defaultValue: 12, min: 0, max: 32 },
      { key: "desktopHeight", label: "Desktop Height (px)", type: "number", defaultValue: 360, min: 200, max: 600 },
      { key: "mobileHeight", label: "Mobile Height (px)", type: "number", defaultValue: 420, min: 200, max: 600 },
    ],
    defaultSettings: {
      image1Url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
      image1Link: "/",
      image1Alt: "Lamps & Lighting",
      image2Url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=800&q=80",
      image2Link: "/",
      image2Alt: "Showpieces & Vases",
      image3Url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
      image3Link: "/",
      image3Alt: "Accent Furniture",
      gap: 12,
      borderRadius: 12,
      desktopHeight: 360,
      mobileHeight: 420,
    },
  },

  /* â”€â”€â”€ Image Banner (full-width clickable banner image) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    type: "FiveGrid",
    label: "5 Grid",
    icon: "LayoutGrid",
    category: "media",
    description: "Five-image promo grid with image upload, alt text, and individual links",
    fields: [
      { key: "image1Url", label: "Image 1 (Tall Left)", type: "image", defaultValue: "" },
      { key: "image1Alt", label: "Image 1 Alt Text", type: "text", defaultValue: "" },
      { key: "image1Link", label: "Image 1 Link", type: "text", defaultValue: "/", placeholder: "/collections/rugs" },
      { key: "image1Title", label: "Image 1 Title", type: "text", defaultValue: "Rugs & Carpets" },
      { key: "image1Offer", label: "Image 1 Offer Text", type: "text", defaultValue: "Up to 50% OFF" },
      { key: "image1Cta", label: "Image 1 Button Text", type: "text", defaultValue: "Shop Now" },
      { key: "image1TextAlign", label: "Image 1 Text Align", type: "select", defaultValue: "left", options: [{ label: "Left", value: "left" }, { label: "Right", value: "right" }] },
      { key: "image2Url", label: "Image 2 (Top Middle)", type: "image", defaultValue: "" },
      { key: "image2Alt", label: "Image 2 Alt Text", type: "text", defaultValue: "" },
      { key: "image2Link", label: "Image 2 Link", type: "text", defaultValue: "/", placeholder: "/collections/mirrors" },
      { key: "image2Title", label: "Image 2 Title", type: "text", defaultValue: "Mirror & Wall Shelves" },
      { key: "image2Offer", label: "Image 2 Offer Text", type: "text", defaultValue: "Up to 40% OFF" },
      { key: "image2Cta", label: "Image 2 Button Text", type: "text", defaultValue: "Shop Now" },
      { key: "image2TextAlign", label: "Image 2 Text Align", type: "select", defaultValue: "left", options: [{ label: "Left", value: "left" }, { label: "Right", value: "right" }] },
      { key: "image3Url", label: "Image 3 (Top Right)", type: "image", defaultValue: "" },
      { key: "image3Alt", label: "Image 3 Alt Text", type: "text", defaultValue: "" },
      { key: "image3Link", label: "Image 3 Link", type: "text", defaultValue: "/", placeholder: "/collections/plants" },
      { key: "image3Title", label: "Image 3 Title", type: "text", defaultValue: "Live Plants & Planters" },
      { key: "image3Offer", label: "Image 3 Offer Text", type: "text", defaultValue: "Up to 48% OFF" },
      { key: "image3Cta", label: "Image 3 Button Text", type: "text", defaultValue: "Shop Now" },
      { key: "image3TextAlign", label: "Image 3 Text Align", type: "select", defaultValue: "left", options: [{ label: "Left", value: "left" }, { label: "Right", value: "right" }] },
      { key: "image4Url", label: "Image 4 (Bottom Middle)", type: "image", defaultValue: "" },
      { key: "image4Alt", label: "Image 4 Alt Text", type: "text", defaultValue: "" },
      { key: "image4Link", label: "Image 4 Link", type: "text", defaultValue: "/", placeholder: "/collections/windchimes" },
      { key: "image4Title", label: "Image 4 Title", type: "text", defaultValue: "Wind Chimes" },
      { key: "image4Offer", label: "Image 4 Offer Text", type: "text", defaultValue: "Up to 50% OFF" },
      { key: "image4Cta", label: "Image 4 Button Text", type: "text", defaultValue: "Shop Now" },
      { key: "image4TextAlign", label: "Image 4 Text Align", type: "select", defaultValue: "left", options: [{ label: "Left", value: "left" }, { label: "Right", value: "right" }] },
      { key: "image5Url", label: "Image 5 (Bottom Right)", type: "image", defaultValue: "" },
      { key: "image5Alt", label: "Image 5 Alt Text", type: "text", defaultValue: "" },
      { key: "image5Link", label: "Image 5 Link", type: "text", defaultValue: "/", placeholder: "/collections/cushions" },
      { key: "image5Title", label: "Image 5 Title", type: "text", defaultValue: "Floor Cushions" },
      { key: "image5Offer", label: "Image 5 Offer Text", type: "text", defaultValue: "Up to 41% OFF" },
      { key: "image5Cta", label: "Image 5 Button Text", type: "text", defaultValue: "Shop Now" },
      { key: "image5TextAlign", label: "Image 5 Text Align", type: "select", defaultValue: "right", options: [{ label: "Left", value: "left" }, { label: "Right", value: "right" }] },
      { key: "gap", label: "Gap (px)", type: "number", defaultValue: 16, min: 8, max: 28 },
      { key: "radius", label: "Corner Radius (px)", type: "number", defaultValue: 22, min: 6, max: 36 },
    ],
    defaultSettings: {
      image1Url: "",
      image1Alt: "",
      image1Link: "/",
      image1Title: "Rugs & Carpets",
      image1Offer: "Up to 50% OFF",
      image1Cta: "Shop Now",
      image1TextAlign: "left",
      image2Url: "",
      image2Alt: "",
      image2Link: "/",
      image2Title: "Mirror & Wall Shelves",
      image2Offer: "Up to 40% OFF",
      image2Cta: "Shop Now",
      image2TextAlign: "left",
      image3Url: "",
      image3Alt: "",
      image3Link: "/",
      image3Title: "Live Plants & Planters",
      image3Offer: "Up to 48% OFF",
      image3Cta: "Shop Now",
      image3TextAlign: "left",
      image4Url: "",
      image4Alt: "",
      image4Link: "/",
      image4Title: "Wind Chimes",
      image4Offer: "Up to 50% OFF",
      image4Cta: "Shop Now",
      image4TextAlign: "left",
      image5Url: "",
      image5Alt: "",
      image5Link: "/",
      image5Title: "Floor Cushions",
      image5Offer: "Up to 41% OFF",
      image5Cta: "Shop Now",
      image5TextAlign: "right",
      gap: 16,
      radius: 22,
    },
  },
  {
    type: "ImageBanner",
    label: "Image Banner",
    icon: "ImageIcon",
    category: "media",
    description: "Full-width promotional banner image with optional link",
    fields: [
      { key: "desktopImageUrl", label: "Desktop Banner Image", type: "image", defaultValue: "" },
      { key: "mobileImageUrl", label: "Mobile Banner Image (optional)", type: "image", defaultValue: "", helpText: "If empty, desktop image will be used on mobile too" },
      { key: "link", label: "Banner Link", type: "text", defaultValue: "/", placeholder: "/collections/sale" },
      { key: "altText", label: "Alt Text", type: "text", defaultValue: "Promotional banner" },
      { key: "desktopHeight", label: "Desktop Height (px)", type: "number", defaultValue: 280, min: 100, max: 600 },
      { key: "mobileHeight", label: "Mobile Height (px)", type: "number", defaultValue: 180, min: 80, max: 400 },
      { key: "borderRadius", label: "Border Radius (px)", type: "number", defaultValue: 12, min: 0, max: 32 },
      { key: "fullWidth", label: "Full Width (edge-to-edge)", type: "toggle", defaultValue: false },
    ],
    defaultSettings: {
      desktopImageUrl: "",
      mobileImageUrl: "",
      link: "/",
      altText: "Promotional banner",
      desktopHeight: 280,
      mobileHeight: 180,
      borderRadius: 12,
      fullWidth: false,
    },
  },

  /* â”€â”€â”€ Reel Image (horizontal scrolling portrait reel) â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    type: "SlideBanner",
    label: "Slide Banner",
    icon: "Images",
    category: "media",
    description: "Auto-sliding image banner with arrow controls and up to 15 slides",
    fields: [
      { key: "heading", label: "Heading (optional)", type: "text", defaultValue: "" },
      { key: "autoPlay", label: "Auto Play", type: "toggle", defaultValue: true },
      { key: "intervalSec", label: "Slide Interval (sec)", type: "number", defaultValue: 4, min: 2, max: 15 },
      { key: "heightDesktop", label: "Desktop Height (px)", type: "number", defaultValue: 360, min: 120, max: 1000 },
      { key: "heightMobile", label: "Mobile Height (px)", type: "number", defaultValue: 220, min: 80, max: 700 },
      { key: "desktopAutoHeight", label: "Desktop Auto Height", type: "toggle", defaultValue: true },
      { key: "mobileAutoHeight", label: "Mobile Auto Height", type: "toggle", defaultValue: true },
      { key: "fitDesktop", label: "Desktop Image Fit", type: "select", defaultValue: "contain", options: [{ label: "Cover", value: "cover" }, { label: "Contain", value: "contain" }] },
      { key: "fitMobile", label: "Mobile Image Fit", type: "select", defaultValue: "contain", options: [{ label: "Contain", value: "contain" }, { label: "Cover", value: "cover" }] },
      { key: "radius", label: "Corner Radius (px)", type: "number", defaultValue: 16, min: 0, max: 36 },
      { key: "slide1Image", label: "Slide 1 Image", type: "image", defaultValue: "" }, { key: "slide1Alt", label: "Slide 1 Alt", type: "text", defaultValue: "" }, { key: "slide1Link", label: "Slide 1 Link", type: "text", defaultValue: "/" },
      { key: "slide2Image", label: "Slide 2 Image", type: "image", defaultValue: "" }, { key: "slide2Alt", label: "Slide 2 Alt", type: "text", defaultValue: "" }, { key: "slide2Link", label: "Slide 2 Link", type: "text", defaultValue: "/" },
      { key: "slide3Image", label: "Slide 3 Image", type: "image", defaultValue: "" }, { key: "slide3Alt", label: "Slide 3 Alt", type: "text", defaultValue: "" }, { key: "slide3Link", label: "Slide 3 Link", type: "text", defaultValue: "/" },
      { key: "slide4Image", label: "Slide 4 Image", type: "image", defaultValue: "" }, { key: "slide4Alt", label: "Slide 4 Alt", type: "text", defaultValue: "" }, { key: "slide4Link", label: "Slide 4 Link", type: "text", defaultValue: "/" },
      { key: "slide5Image", label: "Slide 5 Image", type: "image", defaultValue: "" }, { key: "slide5Alt", label: "Slide 5 Alt", type: "text", defaultValue: "" }, { key: "slide5Link", label: "Slide 5 Link", type: "text", defaultValue: "/" },
      { key: "slide6Image", label: "Slide 6 Image", type: "image", defaultValue: "" }, { key: "slide6Alt", label: "Slide 6 Alt", type: "text", defaultValue: "" }, { key: "slide6Link", label: "Slide 6 Link", type: "text", defaultValue: "/" },
      { key: "slide7Image", label: "Slide 7 Image", type: "image", defaultValue: "" }, { key: "slide7Alt", label: "Slide 7 Alt", type: "text", defaultValue: "" }, { key: "slide7Link", label: "Slide 7 Link", type: "text", defaultValue: "/" },
      { key: "slide8Image", label: "Slide 8 Image", type: "image", defaultValue: "" }, { key: "slide8Alt", label: "Slide 8 Alt", type: "text", defaultValue: "" }, { key: "slide8Link", label: "Slide 8 Link", type: "text", defaultValue: "/" },
      { key: "slide9Image", label: "Slide 9 Image", type: "image", defaultValue: "" }, { key: "slide9Alt", label: "Slide 9 Alt", type: "text", defaultValue: "" }, { key: "slide9Link", label: "Slide 9 Link", type: "text", defaultValue: "/" },
      { key: "slide10Image", label: "Slide 10 Image", type: "image", defaultValue: "" }, { key: "slide10Alt", label: "Slide 10 Alt", type: "text", defaultValue: "" }, { key: "slide10Link", label: "Slide 10 Link", type: "text", defaultValue: "/" },
      { key: "slide11Image", label: "Slide 11 Image", type: "image", defaultValue: "" }, { key: "slide11Alt", label: "Slide 11 Alt", type: "text", defaultValue: "" }, { key: "slide11Link", label: "Slide 11 Link", type: "text", defaultValue: "/" },
      { key: "slide12Image", label: "Slide 12 Image", type: "image", defaultValue: "" }, { key: "slide12Alt", label: "Slide 12 Alt", type: "text", defaultValue: "" }, { key: "slide12Link", label: "Slide 12 Link", type: "text", defaultValue: "/" },
      { key: "slide13Image", label: "Slide 13 Image", type: "image", defaultValue: "" }, { key: "slide13Alt", label: "Slide 13 Alt", type: "text", defaultValue: "" }, { key: "slide13Link", label: "Slide 13 Link", type: "text", defaultValue: "/" },
      { key: "slide14Image", label: "Slide 14 Image", type: "image", defaultValue: "" }, { key: "slide14Alt", label: "Slide 14 Alt", type: "text", defaultValue: "" }, { key: "slide14Link", label: "Slide 14 Link", type: "text", defaultValue: "/" },
      { key: "slide15Image", label: "Slide 15 Image", type: "image", defaultValue: "" }, { key: "slide15Alt", label: "Slide 15 Alt", type: "text", defaultValue: "" }, { key: "slide15Link", label: "Slide 15 Link", type: "text", defaultValue: "/" },
    ],
    defaultSettings: {
      heading: "", autoPlay: true, intervalSec: 4, heightDesktop: 360, heightMobile: 220, desktopAutoHeight: true, mobileAutoHeight: true, fitDesktop: "contain", fitMobile: "contain", radius: 16,
      slide1Image: "", slide1Alt: "", slide1Link: "/", slide2Image: "", slide2Alt: "", slide2Link: "/",
      slide3Image: "", slide3Alt: "", slide3Link: "/", slide4Image: "", slide4Alt: "", slide4Link: "/",
      slide5Image: "", slide5Alt: "", slide5Link: "/", slide6Image: "", slide6Alt: "", slide6Link: "/",
      slide7Image: "", slide7Alt: "", slide7Link: "/", slide8Image: "", slide8Alt: "", slide8Link: "/",
      slide9Image: "", slide9Alt: "", slide9Link: "/", slide10Image: "", slide10Alt: "", slide10Link: "/",
      slide11Image: "", slide11Alt: "", slide11Link: "/", slide12Image: "", slide12Alt: "", slide12Link: "/",
      slide13Image: "", slide13Alt: "", slide13Link: "/", slide14Image: "", slide14Alt: "", slide14Link: "/",
      slide15Image: "", slide15Alt: "", slide15Link: "/",
    },
  },
  {
    type: "SaleBanner",
    label: "Sale Banner",
    icon: "Timer",
    category: "hero",
    description: "Sale campaign banner with live countdown timer",
    fields: [
      { key: "title", label: "Title", type: "text", defaultValue: "Mega Sale Ends Soon" },
      { key: "subtitle", label: "Subtitle", type: "text", defaultValue: "Grab your favorites before the timer runs out" },
      { key: "ctaText", label: "Button Text", type: "text", defaultValue: "Shop Sale" },
      { key: "ctaLink", label: "Button Link", type: "text", defaultValue: "/search" },
      { key: "endDateTime", label: "End Date & Time (ISO)", type: "text", defaultValue: "2026-12-31T23:59:59+05:30", placeholder: "2026-12-31T23:59:59+05:30" },
      { key: "bgFrom", label: "Gradient From", type: "color", defaultValue: "#1b1f3b" },
      { key: "bgTo", label: "Gradient To", type: "color", defaultValue: "#ff6a3d" },
      { key: "textColor", label: "Text Color", type: "color", defaultValue: "#ffffff" },
      { key: "radius", label: "Corner Radius (px)", type: "number", defaultValue: 20, min: 0, max: 40 },
    ],
    defaultSettings: {
      title: "Mega Sale Ends Soon", subtitle: "Grab your favorites before the timer runs out", ctaText: "Shop Sale", ctaLink: "/search",
      endDateTime: "2026-12-31T23:59:59+05:30", bgFrom: "#1b1f3b", bgTo: "#ff6a3d", textColor: "#ffffff", radius: 20,
    },
  },
  {
    type: "NewArrival",
    label: "New Arrival",
    icon: "Sparkles",
    category: "content",
    description: "New arrivals tabbed component with Accessory/Furniture switch and item grid",
    fields: [
      { key: "badgeText", label: "Badge Text", type: "text", defaultValue: "NEW" },
      { key: "title", label: "Title", type: "text", defaultValue: "Arrivals" },
      { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "Be the first to explore our newest furniture and home essentials, crafted for modern homes." },
      { key: "accessoryLabel", label: "Accessory Label", type: "text", defaultValue: "Accessory" },
      { key: "furnitureLabel", label: "Furniture Label", type: "text", defaultValue: "Furniture" },
      { key: "accessoryDataJson", label: "Accessory Data JSON", type: "textarea", defaultValue: "[{\"tab\":\"Wall Decor\",\"items\":[{\"icon\":\"ðŸ–¼ï¸\",\"label\":\"Canvas Art\"},{\"icon\":\"ðŸªž\",\"label\":\"Mirrors\"},{\"icon\":\"ðŸ•¯ï¸\",\"label\":\"Candle Holders\"},{\"icon\":\"ðŸŒ¿\",\"label\":\"Planters\"},{\"icon\":\"ðŸ’¡\",\"label\":\"Wall Lights\"},{\"icon\":\"ðŸŽ¨\",\"label\":\"Paintings\"}]},{\"tab\":\"Beddings\",\"items\":[{\"icon\":\"ðŸ›ï¸\",\"label\":\"Bed Sheets\"},{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"Pillow Covers\"},{\"icon\":\"ðŸ§¸\",\"label\":\"Comforters\"}]},{\"tab\":\"Nursery And Bedding\",\"items\":[{\"icon\":\"ðŸ¼\",\"label\":\"Baby Beds\"},{\"icon\":\"ðŸ§¸\",\"label\":\"Crib Sheets\"},{\"icon\":\"ðŸŒ™\",\"label\":\"Night Lights\"}]},{\"tab\":\"Mosaic\",\"items\":[{\"icon\":\"ðŸ”·\",\"label\":\"Mosaic Tiles\"},{\"icon\":\"ðŸŒ€\",\"label\":\"Art Panels\"},{\"icon\":\"ðŸŽ­\",\"label\":\"Geometric Art\"}]},{\"tab\":\"Rugs\",\"items\":[{\"icon\":\"ðŸŸ«\",\"label\":\"Area Rugs\"},{\"icon\":\"ðŸŸ§\",\"label\":\"Door Mats\"},{\"icon\":\"ðŸŽ­\",\"label\":\"Runner Rugs\"}]}]" },
      { key: "furnitureDataJson", label: "Furniture Data JSON", type: "textarea", defaultValue: "[{\"tab\":\"Sofas & Seating\",\"items\":[{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"3-Seater Sofa\"},{\"icon\":\"ðŸª‘\",\"label\":\"Recliners\"},{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"L-Shape Sofa\"},{\"icon\":\"ðŸª‘\",\"label\":\"Accent Chair\"},{\"icon\":\"ðŸ›ï¸\",\"label\":\"Sofa Cum Bed\"},{\"icon\":\"ðŸŽª\",\"label\":\"Ottoman\"}]},{\"tab\":\"Coffee Table\",\"items\":[{\"icon\":\"â˜•\",\"label\":\"Round Tables\"},{\"icon\":\"ðŸªµ\",\"label\":\"Wooden Tables\"},{\"icon\":\"ðŸ”²\",\"label\":\"Glass Top\"}]},{\"tab\":\"TV Unit\",\"items\":[{\"icon\":\"ðŸ“º\",\"label\":\"Wall Mounted\"},{\"icon\":\"ðŸ—„ï¸\",\"label\":\"Floor Standing\"}]},{\"tab\":\"Study Table\",\"items\":[{\"icon\":\"ðŸ“š\",\"label\":\"Writing Desk\"},{\"icon\":\"ðŸ’¼\",\"label\":\"Computer Desk\"},{\"icon\":\"ðŸ“–\",\"label\":\"Kids Study\"}]},{\"tab\":\"Beds\",\"items\":[{\"icon\":\"ðŸ›ï¸\",\"label\":\"King Size\"},{\"icon\":\"ðŸ›ï¸\",\"label\":\"Queen Size\"},{\"icon\":\"ðŸªµ\",\"label\":\"Wooden Bed\"}]}]" },
      { key: "sectionBgColor2", label: "Section Background", type: "color", defaultValue: "#f0c8bc" },
      { key: "cardBgColor", label: "Container Background", type: "color", defaultValue: "#ffffff" },
      { key: "titleColor", label: "Title Color", type: "color", defaultValue: "#2a1c19" },
      { key: "subtitleColor", label: "Subtitle Color", type: "color", defaultValue: "#7a5550" },
      { key: "accentColor", label: "Accent Color", type: "color", defaultValue: "#d9736a" },
      { key: "badgeTextColor", label: "Badge Text Color", type: "color", defaultValue: "#ffffff" },
      { key: "badgeShadowColor", label: "Badge Shadow Color", type: "color", defaultValue: "#b85a52" },
      { key: "tabTextColor", label: "Tab Text Color", type: "color", defaultValue: "#9a7470" },
      { key: "tabActiveTextColor", label: "Tab Active Text", type: "color", defaultValue: "#d9736a" },
      { key: "tabUnderlineColor", label: "Tab Underline", type: "color", defaultValue: "#d9736a" },
      { key: "tabBorderColor", label: "Tab Border", type: "color", defaultValue: "#f0e6e3" },
      { key: "itemCardBgColor", label: "Item Card Background", type: "color", defaultValue: "#fdf4f3" },
      { key: "itemCardBorderColor", label: "Item Card Border", type: "color", defaultValue: "#f0e0dc" },
      { key: "itemTextColor", label: "Item Text Color", type: "color", defaultValue: "#7a5550" },
      { key: "arrowBgColor", label: "Arrow Background", type: "color", defaultValue: "transparent" },
      { key: "arrowBorderColor", label: "Arrow Border", type: "color", defaultValue: "#e8d8d5" },
      { key: "arrowTextColor", label: "Arrow Text", type: "color", defaultValue: "#7a5550" },    ],
    defaultSettings: {
      badgeText: "NEW",
      title: "Arrivals",
      subtitle: "Be the first to explore our newest furniture and home essentials, crafted for modern homes.",
      accessoryLabel: "Accessory",
      furnitureLabel: "Furniture",
      accessoryDataJson: "[{\"tab\":\"Wall Decor\",\"items\":[{\"icon\":\"ðŸ–¼ï¸\",\"label\":\"Canvas Art\"},{\"icon\":\"ðŸªž\",\"label\":\"Mirrors\"},{\"icon\":\"ðŸ•¯ï¸\",\"label\":\"Candle Holders\"},{\"icon\":\"ðŸŒ¿\",\"label\":\"Planters\"},{\"icon\":\"ðŸ’¡\",\"label\":\"Wall Lights\"},{\"icon\":\"ðŸŽ¨\",\"label\":\"Paintings\"}]},{\"tab\":\"Beddings\",\"items\":[{\"icon\":\"ðŸ›ï¸\",\"label\":\"Bed Sheets\"},{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"Pillow Covers\"},{\"icon\":\"ðŸ§¸\",\"label\":\"Comforters\"}]},{\"tab\":\"Nursery And Bedding\",\"items\":[{\"icon\":\"ðŸ¼\",\"label\":\"Baby Beds\"},{\"icon\":\"ðŸ§¸\",\"label\":\"Crib Sheets\"},{\"icon\":\"ðŸŒ™\",\"label\":\"Night Lights\"}]},{\"tab\":\"Mosaic\",\"items\":[{\"icon\":\"ðŸ”·\",\"label\":\"Mosaic Tiles\"},{\"icon\":\"ðŸŒ€\",\"label\":\"Art Panels\"},{\"icon\":\"ðŸŽ­\",\"label\":\"Geometric Art\"}]},{\"tab\":\"Rugs\",\"items\":[{\"icon\":\"ðŸŸ«\",\"label\":\"Area Rugs\"},{\"icon\":\"ðŸŸ§\",\"label\":\"Door Mats\"},{\"icon\":\"ðŸŽ­\",\"label\":\"Runner Rugs\"}]}]",
      furnitureDataJson: "[{\"tab\":\"Sofas & Seating\",\"items\":[{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"3-Seater Sofa\"},{\"icon\":\"ðŸª‘\",\"label\":\"Recliners\"},{\"icon\":\"ðŸ›‹ï¸\",\"label\":\"L-Shape Sofa\"},{\"icon\":\"ðŸª‘\",\"label\":\"Accent Chair\"},{\"icon\":\"ðŸ›ï¸\",\"label\":\"Sofa Cum Bed\"},{\"icon\":\"ðŸŽª\",\"label\":\"Ottoman\"}]},{\"tab\":\"Coffee Table\",\"items\":[{\"icon\":\"â˜•\",\"label\":\"Round Tables\"},{\"icon\":\"ðŸªµ\",\"label\":\"Wooden Tables\"},{\"icon\":\"ðŸ”²\",\"label\":\"Glass Top\"}]},{\"tab\":\"TV Unit\",\"items\":[{\"icon\":\"ðŸ“º\",\"label\":\"Wall Mounted\"},{\"icon\":\"ðŸ—„ï¸\",\"label\":\"Floor Standing\"}]},{\"tab\":\"Study Table\",\"items\":[{\"icon\":\"ðŸ“š\",\"label\":\"Writing Desk\"},{\"icon\":\"ðŸ’¼\",\"label\":\"Computer Desk\"},{\"icon\":\"ðŸ“–\",\"label\":\"Kids Study\"}]},{\"tab\":\"Beds\",\"items\":[{\"icon\":\"ðŸ›ï¸\",\"label\":\"King Size\"},{\"icon\":\"ðŸ›ï¸\",\"label\":\"Queen Size\"},{\"icon\":\"ðŸªµ\",\"label\":\"Wooden Bed\"}]}]",
      sectionBgColor2: "#f0c8bc",
      cardBgColor: "#ffffff",
      titleColor: "#2a1c19",
      subtitleColor: "#7a5550",
      accentColor: "#d9736a",
      badgeTextColor: "#ffffff",
      badgeShadowColor: "#b85a52",
      tabTextColor: "#9a7470",
      tabActiveTextColor: "#d9736a",
      tabUnderlineColor: "#d9736a",
      tabBorderColor: "#f0e6e3",
      itemCardBgColor: "#fdf4f3",
      itemCardBorderColor: "#f0e0dc",
      itemTextColor: "#7a5550",
      arrowBgColor: "transparent",
      arrowBorderColor: "#e8d8d5",
      arrowTextColor: "#7a5550",    },
  },
  {
    type: "ReelImage",
    label: "Reel Image",
    icon: "Film",
    category: "media",
    description: "Horizontal scrolling portrait image reel with text overlays and links",
    fields: [
      { key: "reel1Image", label: "Reel 1 Image", type: "image", defaultValue: "" },
      { key: "reel1Link", label: "Reel 1 Link", type: "text", defaultValue: "/" },
      { key: "reel1Text", label: "Reel 1 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel2Image", label: "Reel 2 Image", type: "image", defaultValue: "" },
      { key: "reel2Link", label: "Reel 2 Link", type: "text", defaultValue: "/" },
      { key: "reel2Text", label: "Reel 2 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel3Image", label: "Reel 3 Image", type: "image", defaultValue: "" },
      { key: "reel3Link", label: "Reel 3 Link", type: "text", defaultValue: "/" },
      { key: "reel3Text", label: "Reel 3 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel4Image", label: "Reel 4 Image", type: "image", defaultValue: "" },
      { key: "reel4Link", label: "Reel 4 Link", type: "text", defaultValue: "/" },
      { key: "reel4Text", label: "Reel 4 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel5Image", label: "Reel 5 Image", type: "image", defaultValue: "" },
      { key: "reel5Link", label: "Reel 5 Link", type: "text", defaultValue: "/" },
      { key: "reel5Text", label: "Reel 5 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel6Image", label: "Reel 6 Image", type: "image", defaultValue: "" },
      { key: "reel6Link", label: "Reel 6 Link", type: "text", defaultValue: "/" },
      { key: "reel6Text", label: "Reel 6 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel7Image", label: "Reel 7 Image", type: "image", defaultValue: "" },
      { key: "reel7Link", label: "Reel 7 Link", type: "text", defaultValue: "/" },
      { key: "reel7Text", label: "Reel 7 Text (optional)", type: "text", defaultValue: "" },
      { key: "reel8Image", label: "Reel 8 Image", type: "image", defaultValue: "" },
      { key: "reel8Link", label: "Reel 8 Link", type: "text", defaultValue: "/" },
      { key: "reel8Text", label: "Reel 8 Text (optional)", type: "text", defaultValue: "" },
      { key: "heading", label: "Section Heading", type: "text", defaultValue: "" },
      { key: "cardHeight", label: "Card Height (px)", type: "number", defaultValue: 380, min: 250, max: 600 },
      { key: "cardWidth", label: "Card Width (px)", type: "number", defaultValue: 220, min: 150, max: 350 },
      { key: "gap", label: "Gap Between Cards (px)", type: "number", defaultValue: 16, min: 4, max: 32 },
      { key: "borderRadius", label: "Border Radius (px)", type: "number", defaultValue: 16, min: 0, max: 32 },
    ],
    defaultSettings: {
      reel1Image: "", reel1Link: "/", reel1Text: "",
      reel2Image: "", reel2Link: "/", reel2Text: "",
      reel3Image: "", reel3Link: "/", reel3Text: "",
      reel4Image: "", reel4Link: "/", reel4Text: "",
      reel5Image: "", reel5Link: "/", reel5Text: "",
      reel6Image: "", reel6Link: "/", reel6Text: "",
      reel7Image: "", reel7Link: "/", reel7Text: "",
      reel8Image: "", reel8Link: "/", reel8Text: "",
      heading: "",
      cardHeight: 380,
      cardWidth: 220,
      gap: 16,
      borderRadius: 16,
    },
  },
];

/** Lookup a section definition by type */
export function getSectionDef(type: string): SectionDefinition | undefined {
  return sectionRegistry.find((s) => s.type === type);
}



